<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends AbstractRepository
{

    public function search($lastname, $firstname, $order = 'asc', $limit = 20, $offset = 0)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->orderBy('u.id', $order)
        ;
        if ($lastname) {
            $qb->where('u.lastname LIKE ?1')
                ->setParameter(1, '%' . $lastname . '%')
            ;
        }
        if ($firstname) {
            $qb->andWhere('u.firstname LIKE ?2')
                ->setParameter(2, '%' . $firstname . '%')
            ;
        }

        return $this->paginate($qb, $limit, $offset);
    }

}
